### ISSUE TITLE
SAT Command Todo

### ISSUE THREAD

**Issue by m2en** [azisaba/SpicyAzisaTicket#19]
### パーミッション

- `*` - 運営ロール以上を所有するユーザーのみが使用可能
- `^` - グループ管理者(トップ・総裁)のみが使用可能
- `#` - (現状) 法務部のみが使用可能

### 引数

- `<>` - 必須(require)
- `[]` - オプション
----

### 情報系

- [ ] `/help` - ドキュメントへのリンク及びSATの簡単な説明付きEmbedを送信する
- [ ] `/ping` - WebSocketの平均Ping値( `Client#ws` )と [Discord Status](https://discordstatus.com/) へのリンクを表示する
- [ ] `/link` - 各種リンクを送信します。
- [ ] `/docs` - ドキュメントへのリンクを送信します。

### チケット操作系

subgroup: `/ticket`

- [ ] `/ticket create` ・ `/create` - チケットを作成します。(優先)
- [ ] `/ticket delete <channel> [reason]` - 指定したチケットを削除します。 `*` (優先)
- [ ] `/ticket backup <channel>` - 指定したチケットをバックアップします。 `*` (優先)
- [ ] `/ticket add <channel> <user>` - 指定したチケットにメンバーを追加します。 `*` (優先)
- [ ] `/ticket remove <channel> <user>` - 指定したチケットからメンバーを削除します。(運営に対しては効果なし) `*` (優先)
- [ ] `/ticket lock <channel> <reason>` - 指定したチケットをロックします。(ロック中は各操作がブロックされ、鯖民・運営間のメッセージ送信権限を剥奪します。) `^`
- [ ] `/ticket unlock <channel> <reason>` - 指定したチケットのロックを解除します。 `^`

### ユーザー系

subgroup: `/user`

- [ ] `/user ticket-ban <user> <reason>` - ユーザーをチケットBANします。(チケットBAN中は作成等ができません。また、チケット利用中は効果がありません。)`#`
- [ ] `/user ticket-unban <user> <reason>` - ユーザーのチケットBANを解除します。`#`
- [ ] `/user history <user>` - 指定したユーザーのチケット履歴を参照します。`*`
