### ISSUE TITLE
SpicyAzisaTicket Beta Build - Tracking issue

### ISSUE THREAD

**Issue by m2en** [azisaba/SpicyAzisaTicket#2]
### GitHub ( Repository )

- [x] Issue Templateの作成 (テクスチャなどでのみGitHubを利用し、知識があまりないLife等の運営でも気軽に要望などを投げられるように優しいものも用意)
- [x] Pull Request Templateの作成 (主に自分用)
- [ ] eslint, prettierのWorkflowを追加
- [x] README.md の追加

随時追加
